# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 479cc553a65d506554257aa59d29e54c5e42a136e97b936b8dca6259547fe57e7ea739af129f5aa0a087baedf03101ddb5c78b2251018998c63037c46148241d

test:
  secret_key_base: ce6c46a688c70191e5e4bc6cd4364988cd886cccbf71f54a95e3d853d42590e46b538d56d3100accd8d2805f559e7c84d19667a9a1e39063eb72e170f5773ced

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
